apiVersion: saas.nokia.com/v1alpha1
kind: XSFClaim
metadata:
  name: sf-infra-claim
  namespace: crossplane-system
spec:
  parameters:
    # Common Vars
    region: "eu-central-1"
    # Common Tags
    ownerName: "SaaS-Team"
    projectId: "VPC-Crossplane-Project"
    env: "Development"

    # VPC Vars
    vpcName: "vpc-crossplane"
    vpcCidrBlock: "10.0.0.0/16"
    publicSubnetName: "public-subnet"
    publicSubnetACidrBlock: "10.0.10.0/24"
    publicSubnetAAvailabilityZone: "eu-central-1a"
    publicSubnetBCidrBlock: "10.0.20.0/24"
    publicSubnetBAvailabilityZone: "eu-central-1b"
    privateSubnetName: "private-subnet"
    privateSubnetACidrBlock: "10.0.11.0/24"
    privateSubnetAAvailabilityZone: "eu-central-1a"
    privateSubnetBCidrBlock: "10.0.21.0/24"
    privateSubnetBAvailabilityZone: "eu-central-1b"
      
    # RDS Vars
    dbName: "sf-dev-crossplane"
    # identifier: "sf-dev-crossplane-incubator"
    size: "db.t3.micro"
    username: "sfdbadmin"
    engine: "mariadb"
    storageCapacity: 30
    engineVersion: "10.6.14"
    skipFinalSnapshot: true
    publiclyAccessible: false
    autoGeneratePassword: true
    securityGroupName: "sf-dev-mariadb-sg"      
    writeConnectionSecretsToNamespace: "crossplane-system"

    # SQS Vars
    queueName: "sf-dev-crossplane-sqs.fifo"
    fifoQueue: true
    contentBasedDeduplication: false
    delaySeconds: 0
    maximumMessageSize: 2048
    messageRetentionPeriod: 86400
    receiveMessageWaitTimeSeconds: 10
    visibilityTimeout: 30
    sqsManagedSseEnabled: false

    # EKS Vars
    # accountId: "707078929101"
    # provider: "default"
    # permissionsBoundaryPolicy: "policy/NokiaBoundary"
    # clusterName: "eks-crossplane"
    # #eksVpcCidrBlock: "10.0.0.0/24"  # vpcCidrBlock
    # k8s-version: "1.32"
    # capacityType: "ON_DEMAND"
    # imdsV2HttpTokens: "required"
    # nodeGroupDesiredSize: 2
    # nodeGroupMaxSize: 3
    # nodeGroupMinSize: 1
    # nodesImageId: "ami-068faf14a4d1a609e"
    # nodesInstanceType: "t3.medium"
    # nodesLabels:
    #   environment: "development"
    #   team: "SaaS"
    #   project: "SEF-EKS-Crossplane"
    #   common: "true"
    # nodesVolumeSize: 60
    # nodesVolumeType: "gp3"
    # clusterAllowedCidrs:
    #   - "131.228.2.0/27"
    #   - "131.228.32.160/27"
    #   - "37.220.140.34/32"
    #   - "135.245.48.76/32"
    #   - "135.245.48.77/32"
    #   - "135.245.48.86/32"
    #   - "135.245.48.87/32"
    #   - "135.245.20.0/27"