apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xsfs.saas.nokia.com
  labels:
    app.kubernetes.io/version: "v0.1.0"
spec:
  defaultCompositeDeletePolicy: Foreground
  defaultCompositionUpdatePolicy: Manual
  group: saas.nokia.com
  names:
    kind: XSFC
    plural: xsfcs
  claimNames:
    kind: XSFClaim
    plural: xsfclaims
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required:
              - parameters
            properties:
              parameters:
                type: object
                properties:
                  # Common Vars
                  region:
                    type: string
                  # Common Tags
                  ownerName:
                    type: string
                  projectId:
                    type: string
                  env:
                    type: string
                  # VPC Parameters
                  vpcName:
                    type: string
                  vpcCidrBlock:
                    type: string
                  publicSubnetName:
                    type: string
                  publicSubnetACidrBlock:
                    type: string
                  publicSubnetAAvailabilityZone:
                    type: string
                  publicSubnetBCidrBlock:
                    type: string
                  publicSubnetBAvailabilityZone:
                    type: string
                  privateSubnetName:
                    type: string
                  privateSubnetACidrBlock:
                    type: string
                  privateSubnetAAvailabilityZone:
                    type: string
                  privateSubnetBCidrBlock:
                    type: string
                  privateSubnetBAvailabilityZone:
                    type: string
                  # RDS Parameters
                  rdsName:
                    type: string
                  size:
                    type: string
                  username:
                    type: string
                  engine:
                    type: string
                  storageCapacity:
                    type: integer
                  engineVersion:
                    type: string
                  skipFinalSnapshot:
                    type: boolean
                  publiclyAccessible:
                    type: boolean
                  autoGeneratePassword:
                    type: boolean
                  securityGroupName:
                    type: string
                  writeConnectionSecretsToNamespace:
                    type: string
                  # SQS Parameters
                  queueName:
                    type: string
                  fifoQueue:
                    type: boolean
                  contentBasedDeduplication:
                    type: boolean
                  delaySeconds:
                    type: integer
                  maximumMessageSize:
                    type: integer
                  messageRetentionPeriod:
                    type: integer
                  receiveMessageWaitTimeSeconds:
                    type: integer
                  visibilityTimeout:
                    type: integer
                  sqsManagedSseEnabled:
                    type: boolean
          status:
            type: object
            properties:
              vpcId:
                type: string
              privateSubnetIds:
                type: array
                items:
                  type: string
              publicSubnetIds:
                type: array
                items:
                  type: string
              vpcNatGwRootZone1PublicIp:
                type: string
              vpcNatGwRootZone2PublicIp:
                type: string
              # RDS Status
              # address:
              #   type: string
              # port:
              #   type: integer
              # password:
              #   type: string
              # subnetGroupName:
              #   type: string
              # securityGroupId:
              #   type: string
              # identifier:
              #   type: string
              # dbInstanceArn:
              #   type: string
 