# Internet Gateway
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: InternetGateway
metadata:
  name: igw
  namespace: crossplane-system
spec:
  forProvider:
    region: eu-central-1
    vpcIdRef:
      name: test-vpc
    tags:
      Name: igw
