# VPC
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
  name: vpc-crossplane-test
  namespace: crossplane-system
spec:
  forProvider:
    region: eu-central-1
    cidrBlock: "10.0.0.0/16"
    enableDnsSupport: true
    enableDnsHostnames: true
    tags:
      Name: test-vpc
  providerConfigRef:
    name: default
