apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  name: crossplane-bucket-14563456
  namespace: crossplane-system
spec:
  forProvider:
    region: eu-central-1
  providerConfigRef:
    name: default
