apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: saas-aws-crossplane
  namespace: crossplane-system
spec:
  dependsOn:
    - provider: xpkg.upbound.io/upbound/provider-aws-s3
      version: ">=v1.17.0"
    - provider: xpkg.upbound.io/upbound/provider-aws-sqs
      version: ">=v1.0.0"
    - provider: xpkg.upbound.io/upbound/provider-kubernetes
      version: ">=v0.16.0"
    - provider: xpkg.upbound.io/upbound/provider-aws-kms
      version: ">=v1.0.0"
    - provider: xpkg.upbound.io/upbound/provider-aws-rds
      version: ">=v1.0.0"
    - provider: xpkg.upbound.io/upbound/provider-aws-vpc
      version: ">=v1.0.0"
    - provider: xpkg.upbound.io/upbound/provider-aws-ec2
      version: ">=v1.0.0"
    - provider: xpkg.upbound.io/crossplane-contrib/provider-aws
      version: ">=v0.51.4"
    - provider: xpkg.upbound.io/upbound/provider-aws-eks
      version: ">=v1.0.0"
    - provider: xpkg.upbound.io/upbound/provider-aws-iam
      version: ">=v1.0.0"
  crossplane:
    version: ">=v1.18.2"

