apiVersion: saas.nokia.com/v1alpha1
kind: XEKSClaim
metadata:
  name: eks-claim
  namespace: crossplane-system
spec:
  target:
    region: "eu-central-1"
    accountId: "707078929101"
    provider: "default"
    permissionsBoundaryPolicy: "policy/NokiaBoundary"
  root:
    accountId: "707078929101"
  parameters:
    clusterName: "eks-crossplane"
    vpcId: "vpc-0acd66b994175fc04"
    vpcCidrBlock: "10.0.0.0/24" 
    vpcSubnetZone1Id: "subnet-0673e43346fc6723f"
    vpcSubnetZone2Id: "subnet-0ef7d99d0327f4cf3"
    k8s-version: "1.32"
    capacityType: "ON_DEMAND"
    imdsV2HttpTokens: "required"
    nodeGroupDesiredSize: 2
    nodeGroupMaxSize: 3
    nodeGroupMinSize: 1
    nodesImageId: "ami-068faf14a4d1a609e"
    nodesInstanceType: "t3.medium"
    nodesLabels:
      environment: "development"
      team: "SaaS"
      project: "SEF-EKS-Crossplane"
      common: "true"
    nodesVolumeSize: 60
    nodesVolumeType: "gp3"
    vpcNatGwRootZone1PublicIp: "3.68.130.136"
    vpcNatGwRootZone2PublicIp: "52.59.28.47"
    clusterAllowedCidrs:
      - "131.228.2.0/27"
      - "131.228.32.160/27"
      - "37.220.140.34/32"
      - "135.245.48.76/32"
      - "135.245.48.77/32"
      - "135.245.48.86/32"
      - "135.245.48.87/32"
      - "135.245.20.0/27"

